FROM prestashop/prestashop:1.7.7.4-7.3-apache

# Use development php.ini
RUN cp "$PHP_INI_DIR/php.ini-development" "$PHP_INI_DIR/php.ini"

# XDebug extension
RUN pecl install xdebug \
    && docker-php-ext-enable xdebug

# Install Git. Required to run Grumphp
RUN apt-get update \
	&& apt-get install -y git-all

# Install mhsendmail and enable Mailhog
RUN curl -LkSso /usr/bin/mhsendmail 'https://github.com/mailhog/mhsendmail/releases/download/v0.2.0/mhsendmail_linux_amd64'&& \
chmod 0755 /usr/bin/mhsendmail && \
echo 'sendmail_path = "/usr/bin/mhsendmail --smtp-addr=mailhog:1025"' >> /usr/local/etc/php/php.ini;

# Install composer
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer
