services:
  _defaults:
    public: true
    autowire: false
    autoconfigure: false


  ##########
  # Module #
  ##########

  multisafepay:
    class: MultisafepayOfficial
    factory: ['Module', 'getInstanceByName']
    arguments:
      - 'multisafepayofficial'
    public: true

  ############
  # Services #
  ############

  multisafepay.sdk_service:
    class: MultiSafepay\PrestaShop\Services\SdkService
    public: true

  multisafepay.issuer_service:
    class: MultiSafepay\PrestaShop\Services\IssuerService
    arguments:
      - "@multisafepay.sdk_service"
    public: true

  multisafepay.payment_option_service:
    class: MultiSafepay\PrestaShop\Services\PaymentOptionService
    arguments:
      - "@multisafepay"
    public: true

  multisafepay.order_service:
    class: MultiSafepay\PrestaShop\Services\OrderService
    arguments:
      - "@multisafepay"
      - "@multisafepay.sdk_service"
    public: true

  multisafepay.tokenization_service:
    class: MultiSafepay\PrestaShop\Services\TokenizationService
    arguments:
      - "@multisafepay"
      - "@multisafepay.sdk_service"
    public: true

  multisafepay.refund_service:
    class: MultiSafepay\PrestaShop\Services\RefundService
    arguments:
      - "@multisafepay"
      - "@multisafepay.sdk_service"
      - "@multisafepay.payment_option_service"
    public: true

  multisafepay.not_existing_order_notification_service:
    class: MultiSafepay\PrestaShop\Services\NotExistingOrderNotificationService
    arguments:
      - "@multisafepay"
      - "@multisafepay.sdk_service"
      - "@multisafepay.payment_option_service"
      - "@multisafepay.order_service"
    public: true

  multisafepay.existing_order_notification_service:
    class: MultiSafepay\PrestaShop\Services\ExistingOrderNotificationService
    arguments:
      - "@multisafepay"
      - "@multisafepay.sdk_service"
      - "@multisafepay.payment_option_service"
      - "@multisafepay.order_service"
    public: true

  multisafepay.system_status_service:
    class: MultiSafepay\PrestaShop\Services\SystemStatusService
    arguments:
      - "@multisafepay"
    public: true

  ############
  # Builders #
  ############

  multisafepay.address_builder:
    class: MultiSafepay\PrestaShop\Builder\OrderRequest\CustomerBuilder\AddressBuilder
    public: true

  multisafepay.cart_item_builder:
    class: MultiSafepay\PrestaShop\Builder\OrderRequest\ShoppingCartBuilder\CartItemBuilder
    public: true

  multisafepay.discount_item_builder:
    class: MultiSafepay\PrestaShop\Builder\OrderRequest\ShoppingCartBuilder\DiscountItemBuilder
    arguments:
      - "@multisafepay"
    public: true

  multisafepay.shipping_item_builder:
    class: MultiSafepay\PrestaShop\Builder\OrderRequest\ShoppingCartBuilder\ShippingItemBuilder
    arguments:
      - "@multisafepay"
    public: true

  multisafepay.wrapping_item_builder:
    class: MultiSafepay\PrestaShop\Builder\OrderRequest\ShoppingCartBuilder\WrappingItemBuilder
    arguments:
      - "@multisafepay"
    public: true

  multisafepay.customer_builder:
    class: MultiSafepay\PrestaShop\Builder\OrderRequest\CustomerBuilder
    arguments:
      - "@multisafepay.address_builder"
      - "@multisafepay.address_util"
      - "@multisafepay.customer_util"
      - "@multisafepay.language_util"
    public: true

  multisafepay.delivery_builder:
    class: MultiSafepay\PrestaShop\Builder\OrderRequest\DeliveryBuilder
    arguments:
      - "@multisafepay.address_builder"
      - "@multisafepay.address_util"
      - "@multisafepay.customer_util"
      - "@multisafepay.language_util"
    public: true

  multisafepay.description_builder:
    class: MultiSafepay\PrestaShop\Builder\OrderRequest\DescriptionBuilder
    public: true

  multisafepay.gateway_info_builder:
    class: MultiSafepay\PrestaShop\Builder\OrderRequest\GatewayInfoBuilder
    public: true

  multisafepay.payment_component_builder:
    class: MultiSafepay\PrestaShop\Builder\OrderRequest\PaymentComponentBuilder
    public: true

  multisafepay.payment_options_builder:
    class: MultiSafepay\PrestaShop\Builder\OrderRequest\PaymentOptionsBuilder
    arguments:
      - "@multisafepay"
    public: true

  multisafepay.plugin_details_builder:
    class: MultiSafepay\PrestaShop\Builder\OrderRequest\PluginDetailsBuilder
    arguments:
      - "@multisafepay"
    public: true

  multisafepay.second_chance_builder:
    class: MultiSafepay\PrestaShop\Builder\OrderRequest\SecondChanceBuilder
    public: true

  multisafepay.shopping_cart_builder:
    class: MultiSafepay\PrestaShop\Builder\OrderRequest\ShoppingCartBuilder
    arguments:
      - ["@multisafepay.cart_item_builder", "@multisafepay.discount_item_builder", "@multisafepay.shipping_item_builder", "@multisafepay.wrapping_item_builder"]
      - "@multisafepay.currency_util"
    public: true

  multisafepay.time_active_builder:
    class: MultiSafepay\PrestaShop\Builder\OrderRequest\TimeActiveBuilder
    public: true

  multisafepay.tokenization_builder:
    class: MultiSafepay\PrestaShop\Builder\OrderRequest\TokenizationBuilder
    public: true

  multisafepay.order_request_builder:
    class: MultiSafepay\PrestaShop\Builder\OrderRequestBuilder
    arguments:
      - [ "@multisafepay.customer_builder",
          "@multisafepay.delivery_builder",
          "@multisafepay.description_builder",
          "@multisafepay.gateway_info_builder",
          "@multisafepay.payment_component_builder",
          "@multisafepay.payment_options_builder",
          "@multisafepay.plugin_details_builder",
          "@multisafepay.second_chance_builder",
          "@multisafepay.shopping_cart_builder",
          "@multisafepay.time_active_builder",
          "@multisafepay.tokenization_builder" ]
      - "@multisafepay.currency_util"
    public: true

  #########
  # Utils #
  #########

  multisafepay.address_util:
    class: MultiSafepay\PrestaShop\Util\AddressUtil
    public: true

  multisafepay.currency_util:
    class: MultiSafepay\PrestaShop\Util\CurrencyUtil
    public: true

  multisafepay.customer_util:
    class: MultiSafepay\PrestaShop\Util\CustomerUtil
    public: true

  multisafepay.language_util:
    class: MultiSafepay\PrestaShop\Util\LanguageUtil
    public: true
