name: Code sniffer
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  code_sniffer:
    name: Code Sniffer on PHP ${{ matrix.php-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version: ['7.3', '8.1', '8.4']
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '${{ matrix.php-version }}'

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache composer dependencies
        uses: actions/cache@v4
        with:
          path: vendor
          key: composer-${{ runner.os }}-${{ matrix.php-version }}-${{ hashFiles('composer.lock') }}
          restore-keys: |
            composer-${{ runner.os }}-${{ matrix.php-version }}-

      - name: Fetch config files
        run: |
          mkdir -p temp-config
          cd temp-config
          git init
          git remote add origin https://x-access-token:${{ secrets.GLOBAL_GITHUB_TOKEN }}@github.com/MultiSafepay/docker-prestashop.git
          git config core.sparsecheckout true
          echo "include/phpcs.xml" >> .git/info/sparse-checkout
          echo "include/grumphp.yml" >> .git/info/sparse-checkout
          git pull --depth=1 origin main
          cd ..
          cp temp-config/include/phpcs.xml ./phpcs.xml
          cp temp-config/include/grumphp.yml ./grumphp.yml
          rm -rf temp-config

      - name: Install module composer dependencies
        run: composer install

      - name: Run PHP Code Sniffer
        run: composer run-script phpcs
