name: Code sniffer
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  code_sniffer:
    name: Code sniffer
    runs-on: ubuntu-latest
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.3'

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Fetch config files
        run: |
          mkdir -p temp-config
          cd temp-config
          git init
          git remote add origin https://x-access-token:${{ secrets.GLOBAL_GITHUB_TOKEN }}@github.com/MultiSafepay/docker-prestashop.git
          git config core.sparsecheckout true
          echo "include/phpcs.xml" >> .git/info/sparse-checkout
          echo "include/grumphp.yml" >> .git/info/sparse-checkout
          git pull --depth=1 origin main
          cd ..
          cp temp-config/include/phpcs.xml ./phpcs.xml
          cp temp-config/include/grumphp.yml ./grumphp.yml
          rm -rf temp-config

      - name: Install composer dependencies
        run: composer install

      - name: PHP Code Sniffer
        run: composer run-script phpcs
