name: PHPStan
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  php_stan:
    name: PHPStan on PS ${{ matrix.prestashop-version }} & PHP ${{ matrix.php-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        prestashop-version: ['9.0.0']
        php-version: ['8.4']
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '${{ matrix.php-version }}'

      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache composer dependencies
        uses: actions/cache@v4
        with:
          path: vendor
          key: composer-${{ runner.os }}-${{ matrix.php-version }}-${{ hashFiles('composer.lock') }}
          restore-keys: |
            composer-${{ runner.os }}-${{ matrix.php-version }}-

      - name: Download PrestaShop
        run: wget -O prestashop_${{ matrix.prestashop-version }}.zip https://github.com/PrestaShop/PrestaShop/archive/refs/tags/9.0.0.zip

      - name: Sudo chown
        run: sudo chown -R $USER:$USER /var/www/

      - name: Unzip PrestaShop
        run: |
          unzip -o prestashop_${{ matrix.prestashop-version }}.zip
          mkdir -p /var/www/html/application/
          mv PrestaShop-${{ matrix.prestashop-version }}/* /var/www/html/application/
          mv PrestaShop-${{ matrix.prestashop-version }}/.* /var/www/html/application/ 2>/dev/null || true

      - name: Organize the directories
        run: |
          mkdir -p /var/www/html/application/modules/multisafepayofficial
          mv $(ls --ignore=application) /var/www/html/application/modules/multisafepayofficial/
          mv /var/www/html/application/* /var/www/html/
          mv /var/www/html/application/.* /var/www/html/ 2>/dev/null || true

      - name: Install PrestaShop composer dependencies
        run: composer install --working-dir=/var/www/html --no-dev

      - name: Install module composer dependencies
        run: composer install --working-dir=/var/www/html/modules/multisafepayofficial

      - name: Fetch config file
        run: |
          mkdir -p temp-config
          cd temp-config
          git init
          git remote add origin https://x-access-token:${{ secrets.GLOBAL_GITHUB_TOKEN }}@github.com/MultiSafepay/docker-prestashop.git
          git config core.sparsecheckout true
          echo "include/phpstan_stub.php" >> .git/info/sparse-checkout
          echo "include/phpstan.neon" >> .git/info/sparse-checkout
          git pull --depth=1 origin main
          cd ..
          cp temp-config/include/phpstan_stub.php /var/www/html/modules/multisafepayofficial/phpstan_stub.php
          cp temp-config/include/phpstan.neon /var/www/html/modules/multisafepayofficial/phpstan.neon
          rm -rf temp-config

      - name: Run PHPStan
        run: cd /var/www/html/modules/multisafepayofficial && XDEBUG_MODE=off _PS_ROOT_DIR_=./../../ vendor/bin/phpstan analyse --configuration=phpstan.neon --memory-limit 1G --error-format github
