name: PHPStan
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  php_stan:
    name: PHPStan
    runs-on: ubuntu-latest
    strategy:
      matrix:
        presta-versions: ['8.0.1', '8.0.2', '8.0.3']
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'

      - name: Checkout
        uses: actions/checkout@v4

      - name: Download PrestaShop
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          repo: 'prestashop/prestashop'
          version: 'tags/${{ matrix.presta-versions }}'
          file: 'prestashop_${{ matrix.presta-versions }}.zip'
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Sudo chown
        run: sudo chown -R $USER:$USER /var/www/

      - name: Unzip PrestaShop
        run: unzip -o prestashop_${{ matrix.presta-versions }}.zip && unzip -o -d /var/www/html/application prestashop.zip

      - name: Organize the directories
        run: mkdir /var/www/html/application/modules/multisafepayofficial && mv $(ls --ignore=application) /var/www/html/application/modules/multisafepayofficial/ && mv /var/www/html/application/* /var/www/html

      - name: Install composer dependencies
        run: composer install --working-dir=/var/www/html/modules/multisafepayofficial

      - name: Fetch config file
        run: |
          mkdir -p temp-config
          cd temp-config
          git init
          git remote add origin https://x-access-token:${{ secrets.GLOBAL_GITHUB_TOKEN }}@github.com/MultiSafepay/docker-prestashop.git
          git config core.sparsecheckout true
          echo "include/phpstan_stub.php" >> .git/info/sparse-checkout
          echo "include/phpstan.neon" >> .git/info/sparse-checkout
          git pull --depth=1 origin main
          cd ..
          cp temp-config/include/phpstan_stub.php /var/www/html/modules/multisafepayofficial/phpstan_stub.php
          cp temp-config/include/phpstan.neon /var/www/html/modules/multisafepayofficial/phpstan.neon
          rm -rf temp-config

      - name: Run PHPStan
        run: cd /var/www/html/modules/multisafepayofficial && XDEBUG_MODE=off _PS_ROOT_DIR_=./../../ vendor/bin/phpstan analyse --configuration=phpstan.neon --memory-limit 1G --error-format github
